services:
  - type: web
    name: cultivus-app
    runtime: docker
    region: ohio
    plan: starter
    # rootDir indica la carpeta dentro del repositorio donde está el Dockerfile
    rootDir: demo
    # autoDeploy: true hace que Render despliegue automáticamente al hacer push
    autoDeploy: true
    healthCheckPath: /
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      #- key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
      #  sync: false
      #- key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
      #  sync: false
